from pydantic import BaseModel, Field

from robust_library_api.web.api.schema import (
    StandardSuccessResponse,
    StandardSuccessListResponse,
    StandardFailResponse,
    StandardServiceRepositoryErrorResponse
)

class RequestBorrowCreate(BaseModel):
    book_id: int = Field(...)
    reader_name: str = Field(..., max_length=200)

class ResponseBorrow(StandardSuccessResponse): ...

class ResponseBorrowList(StandardSuccessListResponse): ...

class ResponseBorrowNotFoundBorrow(StandardFailResponse): ...
class ResponseBorrowNotFoundBook(StandardFailResponse): ...
class ResponseBorrowBookExhausted(StandardFailResponse): ...
class ResponseBorrowAlreadyClosed(StandardFailResponse): ...
class ResponseBorrowServiceRepositoryError(StandardServiceRepositoryErrorResponse): ...